server:
  port: 8030
  servlet:
    context-path: /token-service


#actuator configuracion
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path:
token:
  expiretime: 1
  cypher: Z3cr10